name: pg8000
version: 1.0.0
description: >
  A port from Python pg8000
#homepage: https://github.com/insinfo/pg8000

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: any #">=2.0.0"
  convert: any #">=1.0.0"
  #
  #enough_convert: ^1.6.0
  #charcode: any #">=1.0.0"
 
  saslprep: ^1.0.2

dev_dependencies:
  test: any
  yaml: any