name: dargres
version: 4.0.0
description: >
  Dargres is a pure-Dart PostgreSQL driver based on Python pg8000
homepage: https://github.com/insinfo/pg8000

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  test: ^1.26.3
  lints: ^5.1.1
