name: dargres
version: 1.0.0
description: >
  Dargres is a pure-Dart PostgreSQL driver based on Python pg8000
homepage: https://github.com/insinfo/pg8000

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ">=2.0.0 <4.0.0" #3.0.2
  convert: ">=1.0.0 <4.0.0" #3.1.1
  collection: '>=1.14.8 <2.0.0'
 
  #enough_convert: ^1.6.0
  #charcode: any #">=1.0.0" 
  #saslprep: ^1.0.2

dev_dependencies:
  #only for test of terrier buffer
  matcher: any #0.12.13 
  benchmark_harness: any #2.2.0
  test: any #1.22.1
  yaml: any #3.1.1